apiVersion: v1
kind: PersistentVolume
metadata:
  name: dataset-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/datasets"  # Path in the host machine
